### ISSUE TITLE
Singleton to reuse TCP connections results in more TCP connections

### ISSUE THREAD

**Issue by kylejw2** [karafka/waterdrop#314] opened 2023-02-03 18:08 UTC
First and foremost, I really appreciate the Karafka library. Well done 👏 

I've finished implementing `waterdrop` into our Kafka producer client. I've been experimenting with a singleton approach. The goal with a singleton is to leave open a small number of TCP connections that can be reused by the producer. Perhaps my implementation is invalid, but my singleton is showing that it's always opening one new TCP connection when the client is called. 
Here's my implementation:
```ruby
# frozen_string_literal: true

require 'singleton'

class Confluent::Kafka::Producer
  include Singleton

  def initialize
    Rails.logger.info { 'Initializing producer' }
    @producer ||= WaterDrop::Producer.new do |config|
      config.deliver = true
      config.logger = Rails.logger

      seed_brokers = ENV.fetch('HOST_IP', nil)

      config.kafka = if seed_brokers.nil?
                       # connect to remote instance
                       {
                         'bootstrap.servers': ENV.fetch('KAFKA_BOOTSTRAP_SERVERS', nil),
                         'security.protocol': 'SASL_SSL',
                         'sasl.username': ENV.fetch('KAFKA_SASL_USERNAME', nil),
                         'sasl.password': ENV.fetch('KAFKA_SASL_PASSWORD', nil),
                         'sasl.mechanisms': 'PLAIN',
                         'request.required.acks': 1
                       }
                     else
                       # connect to local instance
                       {
                         'bootstrap.servers': seed_brokers,
                         'request.required.acks': 1
                       }
                     end
    end
  end

  def produce(message, key, topic)
    Rails.logger.info { "Producing message to topic: #{topic}\tkey: #{key}\tmessage:#{message} " }
    @producer.produce_async(payload: message, key: key, topic: topic)
  rescue StandardError => e
    Rails.logger.error { e.message }
  end
end
```

I was hoping to reuse TCP connections, but running `ss` while in my container's cli is showing that 1. it's not closing TCP connections (desired behavior, since I'm not calling the `close` method and want to reuse connections) and 2. it's always opening a new TCP connection when the client is called.

The docs show that the producer should be closed after it's been used. Is my approach to reuse TCP connections not recommended?

**Comment by mensfeld** [comment] 2023-02-03 18:38
> The docs show that the producer should be closed after it's been used.

Yes. That is after no more messages will ever be produced and the process will exit:

The docs say:

> Creating a producer instance for each message is anyhow a rather bad idea, so we recommend not to.

Here we illustrate a constant based singleton example:

https://github.com/karafka/waterdrop#using-waterdrop-across-the-application-and-with-ruby-on-rails

> I was hoping to reuse TCP connections, but running ss while in my container's cli is showing that 1. it's not closing TCP connections (desired behavior, since I'm not calling the close method and want to reuse connections) and 2. it's always opening a new TCP connection when the client is called.

This is confusing to me: 

You say that "it's not closing TCP connections" and then "it's always opening a new TCP connection"

:confused: 

can you clarify this for me please?

WaterDrop producers are meant to be long-lived. They may however close not used connections if you do not enable it via `socket.keepalive.enable`.

**Comment by mensfeld** [comment] 2023-02-03 18:44
My local demo via `Karafka.producer` (Which is a WaterDrop singleton) shows two TCP connections:

```tcp                ESTAB               0                    0                                                                                         127.0.0.1:9092                                127.0.0.1:51176                             
tcp                ESTAB               0                    0                                                                                         127.0.0.1:9092                                127.0.0.1:51160                             
```

you may also be encountering this:

https://github.com/confluentinc/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

**Comment by mensfeld** [comment] 2023-02-03 18:54
Your demo reduced to this:

```ruby
class Producer
  include Singleton

  def initialize
    Rails.logger.info { 'Initializing producer' }
    @producer ||= WaterDrop::Producer.new do |config|
      config.deliver = true
  config.kafka = {
    'bootstrap.servers': 'localhost:9092',
  }
    end
  end

  def produce(message, key, topic)
    Rails.logger.info { "Producing message to topic: #{topic}\tkey: #{key}\tmessage:#{message} " }
    @producer.produce_async(payload: message, key: key, topic: topic)
  rescue StandardError => e
    Rails.logger.error { e.message }
  end
end
```

also shows 1 TCP connection when using the localhost reference (I used 127 hence two due to link I added previously).

It's worth also adding monitoring and error tracking to your producer before this hits production

**Comment by kylejw2** [comment] 2023-02-03 21:58
I'm realizing now that I'm only experiencing this behavior while in my Sidekiq container. In my rails container, I'm not seeing this same behavior. I was expecting new jobs executed by Sidekiq to use the previous connections, but executing a high-intensity job is resulting in new connections to the same location. 
<img width="660" alt="Screenshot 2023-02-03 at 2 43 10 PM" src="https://user-images.githubusercontent.com/66093447/216718126-1987a681-86fa-444d-8720-a541f1bce229.png">
As described in the screenshot, there are 10 unique connections to the same address.

I appreciate your responses

**Comment by mensfeld** [comment] 2023-02-03 22:08
@kylejw2 can you provide me with more details?
- what workload
- how many threads
- some repro example maybe?
- do you fork sidekiq (aka sidekiq pro, enterprise, etc)?

also - if it is dev, code reload in Sidekiq may have something to do with this - though I never experienced this. Will have to get some more details.

Can you try initializing the instance prior to running jobs? That is actually (just for tests) sending a message via singleton to kafka before actual sidekiq workload?

Waterdrop instances have unique ids (https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/config.rb#L28), you can try connecting a logger and print the debug info and check if there's actually one being used.

**Comment by mensfeld** [comment] 2023-02-03 22:10
I tried to reproduce it in a thread heavy env (50 threads, dispatch loops), same result - no leakage.

**Comment by mensfeld** [comment] 2023-02-06 15:20
Tried with sidekiq today, still can't repro :thinking:

**Comment by kylejw2** [comment] 2023-02-06 15:59
Which version of sidekiq are you using? I'm on 6.4.2

**Comment by kylejw2** [comment] 2023-02-06 17:04
Also, I'm running sidekiq in a different Docker container than my Rails app. Are you also using Docker?

**Comment by mensfeld** [comment] 2023-02-08 15:01
@kylejw2 I do have docker in the container + zookeeper. The rest runs on my machine. If you could create a repro based on https://github.com/karafka/example-apps I will look into that but so far with docker Kafka + Sidekiq 7.0.3 all works well.

**Comment by mensfeld** [comment] 2023-02-08 16:47
Tried now with sidekiq in dev mode: 20 threads, 20 concurrent jobs dispatching to kafka via `Karafka#producer` - constant number of TCP connections as expected. Nothing changing. Same connections in use. Same ports, same connections.

I am closing this one but if you can reproduce it based on the https://github.com/karafka/example-apps I will be more than happy to analyze it and fix it if it is indeed as you say.

**Closed by mensfeld** 2023-02-08 16:47 UTC
Labels: question

**Comment by kylejw2** [comment] 2023-02-08 20:52
Thanks @mensfeld. The help is greatly appreciated. Once I've got a working repro, I'll let you know

**Comment by kylejw2** [comment] 2023-02-09 21:07
I was able to figure out why I was experiencing leaked connections. On the other side of our Rails app, it was using a different client to send messages to Kafka. In one use case, it wasn't closing the connection it was opening. This was a much simpler fix than I was previously anticipating. Lol hopefully others can learn from my mistake 😂 

Thanks again for the help, @mensfeld!

**Comment by mensfeld** [comment] 2023-02-10 18:30
@kylejw2 guess the conclusion is simple: use waterdrop :) no worries :)
